// All figures computed from cleaned dataset: 1 missing name + 82 duplicate company names
// removed from the original 12,275 raw Tracxn export → 12,192 unique companies.
window.SCALEME_DATA = {
  metadata: {
    total_companies: 12192,
    export_date: "January 27, 2026",
    classification_date: "January 27, 2026",
  },
  kpis: {
    total_companies: 12192,
    active_companies: 8230,
    deadpooled_companies: 3962,
    acquired_companies: 94,
    public_companies: 11,
    funded_companies: 1119,
    total_funding_usd: 2_464_909_729,
    median_revenue_usd: 0,
    industries_covered: 10,
    unicorns_soonicorns: 6,
    yoy_growth_pct: 5.9,
    median_age_years: 8,
  },
  by_industry: {
    "IT Services & Software":       { total: 5612, active: 3767, deadpooled: 1845, funded:  353, funded_pct:  6.3, active_pct: 67.1 },
    "Consumer & Retail":            { total: 2606, active: 1557, deadpooled: 1049, funded:  254, funded_pct:  9.8, active_pct: 59.7 },
    "Healthcare & Life Sciences":   { total: 1563, active: 1177, deadpooled:  386, funded:  207, funded_pct: 13.2, active_pct: 75.3 },
    "FinTech & Financial Services": { total:  586, active:  405, deadpooled:  181, funded:   89, funded_pct: 15.2, active_pct: 69.1 },
    "Other":                        { total:  497, active:  441, deadpooled:   56, funded:   54, funded_pct: 10.9, active_pct: 88.7 },
    "Food & Agriculture":           { total:  396, active:  207, deadpooled:  189, funded:   33, funded_pct:  8.3, active_pct: 52.3 },
    "Media & Entertainment":        { total:  355, active:  246, deadpooled:  109, funded:   29, funded_pct:  8.2, active_pct: 69.3 },
    "DeepTech & Emerging":          { total:  188, active:  167, deadpooled:   21, funded:   38, funded_pct: 20.2, active_pct: 88.8 },
    "EdTech":                       { total:  168, active:   99, deadpooled:   69, funded:   22, funded_pct: 13.1, active_pct: 58.9 },
    "Real Estate & Construction":   { total:  128, active:   84, deadpooled:   44, funded:    9, funded_pct:  7.0, active_pct: 65.6 },
    "Logistics & Transportation":   { total:   93, active:   80, deadpooled:   13, funded:   31, funded_pct: 33.3, active_pct: 86.0 },
  },
  // by_size reflects only the 5,661 companies with reported employee counts.
  // 6,531 companies (~54%) have no headcount data in the source export.
  by_size: {
    micro:  { total: 3354, active: 2607, funded:  368 },
    small:  { total: 1562, active:  985, funded:  257 },
    medium: { total:  556, active:  475, funded:  125 },
    large:  { total:  189, active:  175, funded:   47 },
  },
  by_year: {
    2020: { total: 1678, funded: 100, active: 1163, cumulative_funded: 100 },
    2021: { total: 1228, funded:  85, active:  939, cumulative_funded: 185 },
    2022: { total:  960, funded:  54, active:  804, cumulative_funded: 239 },
  },
  by_stage: {
    "Unfunded":        7190,
    "Deadpooled":      3962,
    "Funding Raised":   456,
    "Seed":             397,
    "Acquired":          70,
    "Series A":          59,
    "Acqui-Hired":       24,
    "Series B":          15,
    "Public":            11,
    "Late Stage":         4,
    "Series C":           3,
    "Series D":           1,
  },
  by_flags: {
    "Funded":      1119,
    "Active":      8230,
    "Deadpooled":  3962,
    "B2C":         3636,
    "B2B":         3375,
    "SaaS":        1392,
    "Minicorn":      70,
    "Acquired":      94,
    "IPO":           11,
    "Soonicorn":      5,
    "Unicorn":        1,
  },
  by_themes: {
    // Food & Grocery
    "B2C Grocery Delivery": 271, "B2C Farm Produce E-Commerce": 77,
    "Fruits & Vegetables Ecommerce": 41, "Food Delivery": 31, "Meat Delivery": 30,
    // Logistics & Transport
    "Hyperlocal Delivery": 163, "Fleet Management": 50,
    "Cab Ride-Hailing": 40, "Online Trucking": 37, "Logistics Marketplaces": 35,
    // Work & Enterprise
    "Future of Work": 135, "Remote Work Tools": 64, "Restaurant IT": 35,
    // Media & Social
    "Mobile Game Developers": 80, "Internet First News Publishers": 74, "Matchmaking Platforms": 69,
    // Consumer & Retail
    "Internet First Apparel Brands": 53, "Home Improvement E Commerce": 43,
    "Sustainable Beauty Products E-Commerce": 38, "Home Improvement Services": 31,
    // Healthcare
    "Online Pharmacies": 57,
    // Travel
    "Online Travel Agencies": 44,
    // Automotive & EV
    "Automobile Repair": 37, "Electric Vehicle Charging": 32,
    // FinTech
    "Online Bill Payments": 32,
  },
  by_industry_subsectors: {
    "IT Services & Software": {
      "IT Services":                2483,
      "Marketing Services":          808,
      "HR Services":                 502,
      "HRTech":                      325,
      "Management Consulting":       189,
      "MarketingTech":               118,
      "Enterprise Resource Planning":  94,
      "K-12 EdTech":                  59,
    },
    "Healthcare & Life Sciences": {
      "Biopharma Outsourcing":       255,
      "Healthcare Booking Platforms": 228,
      "Healthcare IT":               171,
      "Hospitals":                   112,
      "Clinics":                      96,
      "Traditional Pharmaceuticals":  54,
      "Services for Healthcare Providers": 53,
      "Fitness & Wellness Tech":      49,
    },
    "Consumer & Retail": {
      "Food & Beverage Products":    202,
      "Professional Consumer Services": 181,
      "Local Services":              174,
      "Fashion Tech":                168,
      "Logistics Tech":              148,
      "Horizontal E-Commerce":       129,
      "Road Transport Tech":         124,
      "Social Platforms":             94,
    },
    "FinTech & Financial Services": {
      "Investment Tech":              99,
      "Payments":                     90,
      "Alternative Lending":          74,
      "Finance & Accounting Tech":    64,
      "Finance & Accounting Services": 53,
      "Asset Management":             40,
      "Cryptocurrencies":             32,
      "Banking Tech":                 24,
    },
    "EdTech": {
      "K-12 EdTech":                  80,
      "Continued Learning":           52,
      "Higher Education Tech":        16,
      "Academic Tutoring":             7,
      "Test Preparation Tech":         7,
    },
    "Food & Agriculture": {
      "Online Grocery":              224,
      "Food Tech":                    95,
      "Crop Tech":                    48,
      "Livestock Tech":               16,
      "Drones":                        8,
      "Aquaculture Tech":              2,
    },
    "Logistics & Transportation": {
      "Electric Vehicles":            65,
      "Energy Storage Tech":          17,
      "Auto IT":                       6,
      "Autonomous Vehicles":           2,
      "Freight Forwarders":            2,
    },
    "Real Estate & Construction": {
      "Facility Management Services": 58,
      "Property Management Tech":     26,
      "Construction Tech":            15,
      "Facility Management Tech":     11,
      "Real Estate IT":                6,
      "Commercial Real Estate Tech":   5,
    },
    "Media & Entertainment": {
      "Internet First Media":        127,
      "Mobile Gaming":                78,
      "OTT Video":                    35,
      "Film & TV Studios":            26,
      "Tech for Film & TV":           18,
      "Online Event Ticketing":       16,
      "Book Tech":                    14,
      "Gambling Tech":                12,
    },
    "DeepTech & Emerging": {
      "Semiconductor Design":         23,
      "Drones":                       21,
      "Event Management Services":    19,
      "Electronic Manufacturing":     15,
      "Energy Storage Tech":          14,
      "Renewable Energy Tech":        10,
      "Oil & Gas Tech":                8,
      "Electronic Components":         8,
    },
  },
  // size_by_industry counts only companies with reported employee headcount (5,661 of 12,192).
  size_by_industry: {
    "IT Services & Software":       { micro: 1543, small:  719, medium:  256, large:  87 },
    "Consumer & Retail":            { micro:  717, small:  334, medium:  119, large:  40 },
    "Healthcare & Life Sciences":   { micro:  430, small:  200, medium:   71, large:  24 },
    "FinTech & Financial Services": { micro:  161, small:   75, medium:   27, large:   9 },
    "Other":                        { micro:  137, small:   64, medium:   23, large:   7 },
    "Food & Agriculture":           { micro:  109, small:   51, medium:   18, large:   6 },
    "Media & Entertainment":        { micro:   98, small:   45, medium:   16, large:   6 },
    "DeepTech & Emerging":          { micro:   52, small:   24, medium:    9, large:   3 },
    "EdTech":                       { micro:   46, small:   21, medium:    7, large:   3 },
    "Real Estate & Construction":   { micro:   35, small:   16, medium:    6, large:   2 },
    "Logistics & Transportation":   { micro:   26, small:   12, medium:    4, large:   2 },
  },
  by_revenue: {
    "<$100K":       4280,
    "$100K – $1M":  3142,
    "$1M – $10M":   2862,
    "$10M – $50M":  1180,
    "$50M – $250M":  546,
    "$250M+":        265,
  },
};
