// Auto-generated by scripts/build_data_js.py — do not edit by hand.
// Source: internal company database, cleaned via sanitize_master.py.
//
// Sample payload illustrating the v2 shape. Re-run build_data_js.py against
// data/companies_clean.csv on each refresh; this file is overwritten.
window.SCALEME_DATA = {
  "metadata": {
    "total_companies": 12210,
    "export_date": "Jan 2026",
    "classification_date": "May 2026",
    "source_label": "ScaleMe Research — Hyderabad Classification, May 2026"
  },
  "kpis": {
    "total_companies":      12210,
    "active_companies":     8239,
    "deadpooled_companies": 3971,
    "acquired_companies":   97,
    "public_companies":     11,
    "funded_companies":     1124,
    "disclosed_funded":     499,
    "total_funding_usd":    2470000000,
    "size_reported":        5664,
    "revenue_reported":     2115,
    "industries_covered":   11,
    "unicorns_soonicorns":  76,
    "yoy_growth_pct":       5.9,
    "median_age_years":     8
  },
  "by_industry": {
    "IT Services & Software":       { "total": 5722, "active": 3941, "deadpooled": 1781, "funded": 306, "funded_pct": 5.3, "active_pct": 68.9 },
    "Healthcare & Life Sciences":   { "total": 1570, "active": 1179, "deadpooled": 391, "funded": 207, "funded_pct": 13.2, "active_pct": 75.1 },
    "Consumer & Retail":            { "total": 2308, "active": 1345, "deadpooled": 963, "funded": 211, "funded_pct": 9.1,  "active_pct": 58.3 },
    "FinTech & Financial Services": { "total": 632,  "active": 437,  "deadpooled": 195, "funded": 99,  "funded_pct": 15.7, "active_pct": 69.1 },
    "EdTech":                       { "total": 273,  "active": 158,  "deadpooled": 115, "funded": 36,  "funded_pct": 13.2, "active_pct": 57.9 },
    "Food & Agriculture":           { "total": 639,  "active": 376,  "deadpooled": 263, "funded": 71,  "funded_pct": 11.1, "active_pct": 58.8 },
    "Logistics & Transportation":   { "total": 20,   "active": 15,   "deadpooled": 5,   "funded": 8,   "funded_pct": 40.0, "active_pct": 75.0 },
    "Real Estate & Construction":   { "total": 107,  "active": 55,   "deadpooled": 52,  "funded": 12,  "funded_pct": 11.2, "active_pct": 51.4 },
    "Media & Entertainment":        { "total": 306,  "active": 212,  "deadpooled": 94,  "funded": 31,  "funded_pct": 10.1, "active_pct": 69.3 },
    "DeepTech & Emerging":          { "total": 549,  "active": 457,  "deadpooled": 92,  "funded": 116, "funded_pct": 21.1, "active_pct": 83.2 },
    "Other":                        { "total": 84,   "active": 64,   "deadpooled": 20,  "funded": 27,  "funded_pct": 32.1, "active_pct": 76.2 }
  },
  "by_size": {
    "micro":  { "total": 3323, "active": 2041, "funded": 43 },
    "small":  { "total": 1576, "active": 1251, "funded": 261 },
    "medium": { "total": 717,  "active": 607,  "funded": 160 },
    "large":  { "total": 48,   "active": 43,   "funded": 17 }
  },
  "by_year": {
    "2012": { "total": 538,  "funded": 64,  "active": 376,  "cumulative_funded": 64 },
    "2013": { "total": 606,  "funded": 63,  "active": 411,  "cumulative_funded": 127 },
    "2014": { "total": 839,  "funded": 90,  "active": 494,  "cumulative_funded": 217 },
    "2015": { "total": 1365, "funded": 155, "active": 737,  "cumulative_funded": 372 },
    "2016": { "total": 1144, "funded": 138, "active": 699,  "cumulative_funded": 510 },
    "2017": { "total": 1103, "funded": 139, "active": 764,  "cumulative_funded": 649 },
    "2018": { "total": 1318, "funded": 126, "active": 921,  "cumulative_funded": 775 },
    "2019": { "total": 1445, "funded": 104, "active": 945,  "cumulative_funded": 879 },
    "2020": { "total": 1668, "funded": 99,  "active": 1156, "cumulative_funded": 978 },
    "2021": { "total": 1221, "funded": 84,  "active": 933,  "cumulative_funded": 1062 },
    "2022": { "total": 954,  "funded": 53,  "active": 799,  "cumulative_funded": 1115 },
    "2023": { "total": 412,  "funded": 6,   "active": 372,  "cumulative_funded": 1121 },
    "2024": { "total": 188,  "funded": 2,   "active": 178,  "cumulative_funded": 1123 },
    "2025": { "total": 54,   "funded": 1,   "active": 53,   "cumulative_funded": 1124 }
  },
  "by_stage": {
    "Unfunded":       7203,
    "Seed":           395,
    "Funding Raised": 456,
    "Series A":       59,
    "Series B":       15,
    "Series C":       3,
    "Series D":       1,
    "Late Stage":     4,
    "Public":         11,
    "Acquired":       70,
    "Acqui-Hired":    24,
    "Deadpooled":     3971
  },
  "by_themes": {
    "B2C Grocery Delivery": 270, "Hyperlocal Delivery": 162, "Future of Work": 134,
    "Mobile Game Developers": 80, "B2C Farm Produce E-Commerce": 77, "Internet First News Publishers": 73,
    "Matchmaking Platforms": 69, "Remote Work Tools": 64, "Online Pharmacies": 57,
    "Internet First Apparel Brands": 53, "Fleet Management": 50, "Online Travel Agencies": 44,
    "Home Improvement E Commerce": 43, "Fruits & Vegetables Ecommerce": 41, "Cab Ride-Hailing": 40,
    "Sustainable Beauty Products E-Commerce": 38, "Online Trucking": 37, "Automobile Repair": 37,
    "Logistics Marketplaces": 35, "Restaurant IT": 35, "Electric Vehicle Charging": 32,
    "Online Bill Payments": 32, "Home Improvement Services": 31, "Food Delivery": 31,
    "Meat Delivery": 30, "Precision Farming": 29, "Doctor Appointment Booking": 29,
    "Fitness and Diet Apps": 28, "Mobile Marketing": 27, "CRM for Enterprises": 27,
    "Data Security": 27, "At Home Fitness": 26, "Real Money Gaming": 25, "Ondemand Laundry Services": 25,
    "Organic Farming": 24, "Commercial Drones": 23, "Nutritional Formula": 23,
    "Project Management Tools": 23, "Enterprise Communication": 23, "Internet First Snack Brands": 22,
    "OTT Streaming Platforms": 21, "Live Chat Software": 21, "HRMS for SMBs": 21,
    "HRMS for Enterprises": 20, "Ad Network": 20, "Applicant Testing Platforms": 19,
    "Video On Demand": 18, "Retail POS Solutions": 18, "Enterprise Document Management": 18,
    "Enterprise Content Management": 18
  },
  "by_industry_subsectors": {
    "IT Services & Software": { "IT Services": 2641, "Marketing Services": 968, "HR Services": 540, "HRTech": 357, "Management Consulting Services": 203, "Enterprise Resource Planning": 190, "MarketingTech": 178, "AI Services": 131, "Mobile Gaming": 89, "Sales Force Automation": 83, "Cybersecurity": 72, "Enterprise Collaboration": 68 },
    "Healthcare & Life Sciences": { "Biopharma Outsourcing": 260, "Healthcare Booking Platforms": 247, "Healthcare IT": 232, "Hospitals": 113, "Clinics": 96, "Life Sciences Tech": 68, "Fitness & Wellness Tech": 63, "Services for Healthcare Providers": 55, "Traditional Pharmaceuticals": 54, "Clinic Chains": 47, "Hospital Chains": 44, "Life Sciences Platforms and Tools": 37 },
    "Consumer & Retail": { "Fashion Tech": 408, "Local Services": 295, "Food & Beverage Products": 215, "Logistics Tech": 198, "Professional Consumer Services": 192, "Road Transport Tech": 164, "Social Platforms": 133, "Horizontal E-Commerce": 133, "Online Travel": 112, "Beauty Tech": 96, "Wedding Tech": 91, "B2B E-Commerce": 87 },
    "FinTech & Financial Services": { "Investment Tech": 120, "Payments": 112, "Alternative Lending": 90, "Finance & Accounting Tech": 81, "Finance & Accounting Services": 53, "Asset Management": 44, "Cryptocurrencies": 38, "Banking Tech": 37, "Consumer and SME Loans": 26, "Insurance Distribution": 24, "Services for Investment Industry": 23, "Crowdfunding": 16 },
    "EdTech": { "K-12 EdTech": 251, "Higher Education Tech": 82, "Continued Learning": 76, "Academic Tutoring": 16, "Pre-K EdTech": 15, "Test Preparation Tech": 14, "Educational Support Services": 4, "Continuing Education Chains": 1 },
    "Food & Agriculture": { "Online Grocery": 293, "Food & Beverage Products": 215, "Food Tech": 125, "Crop Tech": 96, "Livestock Tech": 39, "Alcoholic Beverage Products": 5, "Food Processing": 4, "Aquaculture Tech": 3, "Food Service Chains": 3, "Food Distributors": 2, "Crop Farming": 1, "Food Retailers": 1 },
    "Logistics & Transportation": { "Road Transport Tech": 165, "Electric Vehicles": 96, "Auto E-Commerce & Content": 72, "Auto Retail & Aftersales": 49, "Connected Vehicles": 12, "Auto IT": 9, "Autonomous Vehicles": 4, "Flying Cars": 2, "Freight Forwarders": 2, "Auto Components": 1, "Hyperloop": 1 },
    "Real Estate & Construction": { "Residential Real Estate Tech": 76, "Facility Management Services": 64, "Property Management Tech": 56, "Construction Tech": 48, "Commercial Real Estate Tech": 34, "Facility Management Tech": 34, "Real Estate IT": 17, "Building Materials": 2, "Real Estate & Infrastructure Developers": 1, "Senior Housing": 1, "Construction Equipment and Machinery": 1 },
    "Media & Entertainment": { "Internet First Media": 148, "Social Platforms": 133, "Mobile Gaming": 89, "OTT Video": 40, "Tech for Film & TV": 39, "Online Photos": 34, "Film & TV Studios": 26, "Online Event Ticketing": 23, "Music Tech": 20, "Gambling Tech": 20, "Book Tech": 18, "Radio Tech": 12 },
    "DeepTech & Emerging": { "Aerospace & Defence": 77, "Electric Vehicles": 96, "Manufacturing Services": 90, "Energy Storage Tech": 48, "Chatbots": 45, "Security & Surveillance Technology": 42, "Drones": 40, "Manufacturing Tech": 40, "IoT Applications": 34, "Energy Efficiency Tech": 29, "Semiconductor Design and Manufacturing Services": 24, "Wearable Technology": 23 },
    "Other": { "Road Transport Tech": 329, "Local Services": 295, "Logistics Tech": 198, "Online Travel": 112, "Artificial Intelligence": 65, "Energy Efficiency Tech": 58, "Drones": 40, "Cryptocurrencies": 38, "IoT Applications": 34, "Renewable Energy Tech": 34, "Solid Waste Management Tech": 26, "Blockchain Services": 25 }
  },
  "size_by_industry": {
    "IT Services & Software":       { "micro": 1858, "small": 856, "medium": 265, "large": 20 },
    "Healthcare & Life Sciences":   { "micro": 320,  "small": 181, "medium": 151, "large": 15 },
    "Consumer & Retail":            { "micro": 478,  "small": 215, "medium": 115, "large": 3  },
    "FinTech & Financial Services": { "micro": 195,  "small": 79,  "medium": 47,  "large": 5  },
    "EdTech":                       { "micro": 88,   "small": 33,  "medium": 12,  "large": 0  },
    "Food & Agriculture":           { "micro": 154,  "small": 56,  "medium": 36,  "large": 1  },
    "Logistics & Transportation":   { "micro": 9,    "small": 5,   "medium": 0,   "large": 0  },
    "Real Estate & Construction":   { "micro": 32,   "small": 17,  "medium": 4,   "large": 0  },
    "Media & Entertainment":        { "micro": 79,   "small": 31,  "medium": 13,  "large": 1  },
    "DeepTech & Emerging":          { "micro": 95,   "small": 77,  "medium": 43,  "large": 2  },
    "Other":                        { "micro": 15,   "small": 11,  "medium": 12,  "large": 1  }
  },
  "by_revenue": {
    "< $100K":       388,
    "$100K – $1M":   712,
    "$1M – $10M":    645,
    "$10M – $100M":  287,
    "$100M+":        83
  },
  "funding_events_by_year": {
    "2015": { "rounds": 18, "total_usd": 58000000,  "median_round": 600000 },
    "2016": { "rounds": 27, "total_usd": 86000000,  "median_round": 700000 },
    "2017": { "rounds": 38, "total_usd": 132000000, "median_round": 950000 },
    "2018": { "rounds": 52, "total_usd": 198000000, "median_round": 1400000 },
    "2019": { "rounds": 64, "total_usd": 261000000, "median_round": 1800000 },
    "2020": { "rounds": 68, "total_usd": 305000000, "median_round": 2000000 },
    "2021": { "rounds": 78, "total_usd": 412000000, "median_round": 3400000 },
    "2022": { "rounds": 85, "total_usd": 478000000, "median_round": 2800000 },
    "2023": { "rounds": 82, "total_usd": 268000000, "median_round": 1800000 },
    "2024": { "rounds": 79, "total_usd": 196000000, "median_round": 1200000 },
    "2025": { "rounds": 42, "total_usd": 76000000,  "median_round": 1000000 }
  },
  "top_investors": [
    { "name": "CIE IIITH",              "deals": 70, "type": "accelerator",  "active": true },
    { "name": "BIRAC",                  "deals": 47, "type": "govt_backed",  "active": true },
    { "name": "T-Hub",                  "deals": 40, "type": "accelerator",  "active": true },
    { "name": "C-CAMP",                 "deals": 24, "type": "govt_backed",  "active": true },
    { "name": "Clay Capital",           "deals": 22, "type": "vc",           "active": true },
    { "name": "10000 Startups",         "deals": 18, "type": "accelerator",  "active": true },
    { "name": "AIC-CCMB",               "deals": 17, "type": "govt_backed",  "active": true },
    { "name": "LetsVenture",            "deals": 16, "type": "syndicate",    "active": true },
    { "name": "Brand Capital",          "deals": 15, "type": "vc",           "active": true },
    { "name": "Hyderabad Angels",       "deals": 14, "type": "angel_group",  "active": true },
    { "name": "IIIT Hyderabad",         "deals": 14, "type": "accelerator",  "active": true },
    { "name": "Y Combinator",           "deals": 12, "type": "vc",           "active": true },
    { "name": "SR Innovation Exchange", "deals": 12, "type": "accelerator",  "active": true },
    { "name": "WE Hub",                 "deals": 12, "type": "govt_backed",  "active": true },
    { "name": "Indian Angel Network",   "deals": 10, "type": "angel_group",  "active": true }
  ],
  "heatmap_stages": ["Unfunded", "Seed", "Funding Raised", "Series A", "Series B", "Series C", "Series D+", "Public/Acquired"],
  "sector_stage_matrix": {
    "IT Services & Software":       { "Unfunded": 3618, "Seed": 138, "Funding Raised": 128, "Series A": 14, "Series B": 6, "Series C": 1, "Series D+": 1, "Public/Acquired": 35 },
    "Healthcare & Life Sciences":   { "Unfunded": 971,  "Seed": 84,  "Funding Raised": 79,  "Series A": 10, "Series B": 3, "Series C": 1, "Series D+": 1, "Public/Acquired": 30 },
    "Consumer & Retail":            { "Unfunded": 1134, "Seed": 79,  "Funding Raised": 94,  "Series A": 13, "Series B": 4, "Series C": 0, "Series D+": 0, "Public/Acquired": 21 },
    "FinTech & Financial Services": { "Unfunded": 333,  "Seed": 44,  "Funding Raised": 41,  "Series A": 8,  "Series B": 3, "Series C": 1, "Series D+": 0, "Public/Acquired": 7  },
    "EdTech":                       { "Unfunded": 122,  "Seed": 14,  "Funding Raised": 15,  "Series A": 4,  "Series B": 1, "Series C": 0, "Series D+": 0, "Public/Acquired": 2  },
    "Food & Agriculture":           { "Unfunded": 305,  "Seed": 29,  "Funding Raised": 32,  "Series A": 4,  "Series B": 1, "Series C": 0, "Series D+": 0, "Public/Acquired": 5  },
    "Logistics & Transportation":   { "Unfunded": 7,    "Seed": 3,   "Funding Raised": 3,   "Series A": 1,  "Series B": 0, "Series C": 0, "Series D+": 0, "Public/Acquired": 1  },
    "Real Estate & Construction":   { "Unfunded": 43,   "Seed": 4,   "Funding Raised": 5,   "Series A": 2,  "Series B": 0, "Series C": 0, "Series D+": 0, "Public/Acquired": 1  },
    "Media & Entertainment":        { "Unfunded": 181,  "Seed": 11,  "Funding Raised": 14,  "Series A": 2,  "Series B": 1, "Series C": 0, "Series D+": 0, "Public/Acquired": 3  },
    "DeepTech & Emerging":          { "Unfunded": 341,  "Seed": 24,  "Funding Raised": 37,  "Series A": 5,  "Series B": 2, "Series C": 0, "Series D+": 2, "Public/Acquired": 48 },
    "Other":                        { "Unfunded": 39,   "Seed": 8,   "Funding Raised": 8,   "Series A": 5,  "Series B": 1, "Series C": 0, "Series D+": 1, "Public/Acquired": 2  }
  },
  "concentration": [
    { "rank": 5,   "label": "Top 5",   "count": 5,   "share_pct": 27.0 },
    { "rank": 25,  "label": "Top 25",  "count": 25,  "share_pct": 58.0 },
    { "rank": 50,  "label": "Top 50",  "count": 50,  "share_pct": 73.0 },
    { "rank": 125, "label": "Top 125", "count": 125, "share_pct": 91.0 }
  ],
  "concentration_denominator": 499,
  "defence_spotlight": {
    "company_count": 77,
    "ipo_count":     7,
    "total_raised":  180000000,
    "top10_funded": [99000000, 22000000, 18000000, 12000000, 9000000, 6000000, 5000000, 4000000, 3000000, 2000000],
    "ipo_years":    [2007, 2014, 2018, 2019, 2022, 2023, 2024]
  }
};
