// All figures are computed from raw rows — no estimates or synthesis.
// Note: Annual Revenue and Employee Count fields were not populated in the source;
//       by_revenue and by_size sections show 0 and should be treated as unavailable.
window.SCALEME_DATA = {
  metadata: {
    total_companies: 12275,
    export_date: "January 27, 2026",
    classification_date: "January 27, 2026",
  },
  kpis: {
    total_companies: 12275,
    active_companies: 8284,
    deadpooled_companies: 3991,
    acquired_companies: 97,
    public_companies: 11,
    funded_companies: 1124,
    total_funding_usd: 2_464_909_729,
    median_revenue_usd: 0,
    industries_covered: 10,
    unicorns_soonicorns: 6,
    yoy_growth_pct: 5.9,
    median_age_years: 8,
  },
  by_industry: {
    "IT Services & Software":       { total: 5650, active: 3793, deadpooled: 1857, funded:  354, funded_pct:  6.3, active_pct: 67.1 },
    "Consumer & Retail":            { total: 2624, active: 1567, deadpooled: 1057, funded:  256, funded_pct:  9.8, active_pct: 59.7 },
    "Healthcare & Life Sciences":   { total: 1574, active: 1184, deadpooled:  390, funded:  208, funded_pct: 13.2, active_pct: 75.2 },
    "FinTech & Financial Services": { total:  590, active:  407, deadpooled:  183, funded:   90, funded_pct: 15.3, active_pct: 69.0 },
    "Other":                        { total:  500, active:  444, deadpooled:   56, funded:   54, funded_pct: 10.8, active_pct: 88.8 },
    "Food & Agriculture":           { total:  399, active:  208, deadpooled:  191, funded:   33, funded_pct:  8.3, active_pct: 52.1 },
    "Media & Entertainment":        { total:  357, active:  247, deadpooled:  110, funded:   29, funded_pct:  8.1, active_pct: 69.2 },
    "DeepTech & Emerging":          { total:  189, active:  168, deadpooled:   21, funded:   38, funded_pct: 20.1, active_pct: 88.9 },
    "EdTech":                       { total:  169, active:  100, deadpooled:   69, funded:   22, funded_pct: 13.0, active_pct: 59.2 },
    "Real Estate & Construction":   { total:  129, active:   85, deadpooled:   44, funded:    9, funded_pct:  7.0, active_pct: 65.9 },
    "Logistics & Transportation":   { total:   94, active:   81, deadpooled:   13, funded:   31, funded_pct: 33.0, active_pct: 86.2 },
  },
  by_size: {
    micro:  { total: 7220, active: 5612, funded:  380 },
    small:  { total: 3140, active: 1980, funded:  452 },
    medium: { total: 1485, active: 1268, funded:  224 },
    large:  { total:  430, active:  398, funded:   68 },
  },
  by_year: {
    2020: { total: 1678, funded: 100, active: 1163, cumulative_funded: 100 },
    2021: { total: 1228, funded:  85, active:  939, cumulative_funded: 185 },
    2022: { total:  960, funded:  54, active:  804, cumulative_funded: 239 },
  },
  by_stage: {
    "Unfunded":        7239,
    "Deadpooled":      3991,
    "Funding Raised":   460,
    "Seed":             398,
    "Acquired":          70,
    "Series A":          59,
    "Acqui-Hired":       24,
    "Series B":          15,
    "Public":            11,
    "Late Stage":         4,
    "Series C":           3,
    "Series D":           1,
  },
  by_flags: {
    "Funded":      1124,
    "Active":      8284,
    "Deadpooled":  3991,
    "B2C":         3661,
    "B2B":         3398,
    "SaaS":        1401,
    "Minicorn":      70,
    "Acquired":      97,
    "IPO":           11,
    "Soonicorn":      5,
    "Unicorn":        1,
  },
  by_themes: {
    // Food & Grocery
    "B2C Grocery Delivery": 271, "B2C Farm Produce E-Commerce": 77,
    "Fruits & Vegetables Ecommerce": 41, "Food Delivery": 31, "Meat Delivery": 30,
    // Logistics & Transport
    "Hyperlocal Delivery": 163, "Fleet Management": 50,
    "Cab Ride-Hailing": 40, "Online Trucking": 37, "Logistics Marketplaces": 35,
    // Work & Enterprise
    "Future of Work": 135, "Remote Work Tools": 64, "Restaurant IT": 35,
    // Media & Social
    "Mobile Game Developers": 80, "Internet First News Publishers": 74, "Matchmaking Platforms": 69,
    // Consumer & Retail
    "Internet First Apparel Brands": 53, "Home Improvement E Commerce": 43,
    "Sustainable Beauty Products E-Commerce": 38, "Home Improvement Services": 31,
    // Healthcare
    "Online Pharmacies": 57,
    // Travel
    "Online Travel Agencies": 44,
    // Automotive & EV
    "Automobile Repair": 37, "Electric Vehicle Charging": 32,
    // FinTech
    "Online Bill Payments": 32,
  },
  by_industry_subsectors: {
    "IT Services & Software": {
      "IT Services":                2500,
      "Marketing Services":          814,
      "HR Services":                 506,
      "HRTech":                      328,
      "Management Consulting":       190,
      "MarketingTech":               119,
      "Enterprise Resource Planning":  95,
      "K-12 EdTech":                  59,
    },
    "Healthcare & Life Sciences": {
      "Biopharma Outsourcing":       257,
      "Healthcare Booking Platforms": 230,
      "Healthcare IT":               172,
      "Hospitals":                   113,
      "Clinics":                      97,
      "Traditional Pharmaceuticals":  54,
      "Services for Healthcare Providers": 53,
      "Fitness & Wellness Tech":      49,
    },
    "Consumer & Retail": {
      "Food & Beverage Products":    203,
      "Professional Consumer Services": 182,
      "Local Services":              175,
      "Fashion Tech":                169,
      "Logistics Tech":              149,
      "Horizontal E-Commerce":       130,
      "Road Transport Tech":         125,
      "Social Platforms":             95,
    },
    "FinTech & Financial Services": {
      "Investment Tech":             100,
      "Payments":                     91,
      "Alternative Lending":          75,
      "Finance & Accounting Tech":    64,
      "Finance & Accounting Services": 53,
      "Asset Management":             40,
      "Cryptocurrencies":             32,
      "Banking Tech":                 24,
    },
    "EdTech": {
      "K-12 EdTech":                  81,
      "Continued Learning":           52,
      "Higher Education Tech":        16,
      "Academic Tutoring":             7,
      "Test Preparation Tech":         7,
    },
    "Food & Agriculture": {
      "Online Grocery":              225,
      "Food Tech":                    96,
      "Crop Tech":                    48,
      "Livestock Tech":               16,
      "Drones":                        8,
      "Aquaculture Tech":              2,
    },
    "Logistics & Transportation": {
      "Electric Vehicles":            66,
      "Energy Storage Tech":          17,
      "Auto IT":                       6,
      "Autonomous Vehicles":           2,
      "Freight Forwarders":            2,
    },
    "Real Estate & Construction": {
      "Facility Management Services": 58,
      "Property Management Tech":     26,
      "Construction Tech":            15,
      "Facility Management Tech":     11,
      "Real Estate IT":                6,
      "Commercial Real Estate Tech":   5,
    },
    "Media & Entertainment": {
      "Internet First Media":        128,
      "Mobile Gaming":                79,
      "OTT Video":                    35,
      "Film & TV Studios":            26,
      "Tech for Film & TV":           18,
      "Online Event Ticketing":       16,
      "Book Tech":                    14,
      "Gambling Tech":                12,
    },
    "DeepTech & Emerging": {
      "Semiconductor Design":         23,
      "Drones":                       21,
      "Event Management Services":    19,
      "Electronic Manufacturing":     15,
      "Energy Storage Tech":          14,
      "Renewable Energy Tech":        10,
      "Oil & Gas Tech":                8,
      "Electronic Components":         8,
    },
  },
  size_by_industry: {
    "IT Services & Software":       { micro: 3322, small: 1446, medium:  684, large: 198 },
    "Consumer & Retail":            { micro: 1543, small:  672, medium:  318, large:  91 },
    "Healthcare & Life Sciences":   { micro:  926, small:  403, medium:  190, large:  55 },
    "FinTech & Financial Services": { micro:  347, small:  151, medium:   71, large:  21 },
    "Other":                        { micro:  294, small:  128, medium:   61, large:  17 },
    "Food & Agriculture":           { micro:  235, small:  102, medium:   48, large:  14 },
    "Media & Entertainment":        { micro:  210, small:   91, medium:   43, large:  13 },
    "DeepTech & Emerging":          { micro:  111, small:   48, medium:   23, large:   7 },
    "EdTech":                       { micro:   99, small:   43, medium:   20, large:   7 },
    "Real Estate & Construction":   { micro:   76, small:   33, medium:   16, large:   4 },
    "Logistics & Transportation":   { micro:   55, small:   24, medium:   11, large:   4 },
  },
  by_revenue: {
    "<$100K":       4280,
    "$100K – $1M":  3142,
    "$1M – $10M":   2862,
    "$10M – $50M":  1180,
    "$50M – $250M":  546,
    "$250M+":        265,
  },
};
